### ISSUE TITLE
Request for textures (Substratum)

### ISSUE THREAD

**Issue by Endmateria** [FaithfulTeam/FaithfulMods#7]
This is just a request, no issues.  Love your pack and I was just wondering if you guys have done, or can do textures for the Substratum mod?  It's a pretty popular ore mod that works hand in hand with Foundry (both done by the same author). https://minecraft.curseforge.com/projects/substratum

**Comment by MarikCZ** [comment]
Why not? But I have in queue very simillar mod "Hardcore ore". It will be easy too. :)

**Comment by Endmateria** [comment]
Yeah I looked at his mod a week ago, looks like he's moving pretty quickly on it.  From the look of it, he uses a lot of the same ores... you could probably use the same textures for duplicate ores between the two mods huh?  Also, from what I was reading, the hardcore ores maker has two sets of textures for his ores floating around.  I guess he redid them, but a couple people like the old ones better.  Just thought I'd throw that out there, in case you might want to see both so you can pick your favorites.  Thanks again for all your hard work bringing all of these modded textures together though.... really appreciate it.

**Comment by MarikCZ** [comment]
Oh, THANK YOU SO MUCH!

You have very good idea about dupliciting mods, but I don't like same textures for different "types".
Main cause you little bit talked about. I have for example copper ore. One from Thermal Expansion, second from IC2 and at last third from Forestry. If I use same textures, you must first open JEI/NEI to determine from which mod the ore is. But If i use orange, brown and greenish brown, determining is very easy. So orange = TherEx, brown = IC2 and greenish brown = Forestry.
Unfortunately most of ores are white or grey. You can name it but...never ending. So. Tin, Silver, Alumin(i)um (Bauxite), Lead, Nickel, Osmium, Zinc, Titan(ium), Platinum, Chrom(ium), Mangan(ese), Mercury...UGH!!! Who want draw it?, heh!?

I think you must understand. :D

**Comment by Endmateria** [comment]
Yeah, I totally understand why you would want to keep all the ores unique, albeit being a pain in the ass hahah.  Then again, most of the serious modders out there are probably going to be using mods that tell them what mod the ore belongs to, making the need of texture differences redundant e.g.,  mods like the One Probe, or Waila.  In my worlds, I personally don't like when different mods add the same ore... it makes a mess.  Like if forestry adds tin and copper, then I tell substratum NOT to add those two ores.  Regardless, some people like to add all the ores from all the mods all at once, and in that respect I empathize with your dilemma hahaha

**Comment by MarikCZ** [comment]
Yes, config is actually in mods implemented. But when you have copper ingot. Heh?

**Comment by Endmateria** [comment]
Yeah, those should be different, or else you have a confusing situation where all the copper ingots look the same, but they don't universally work in recipes (unless you use a unified ore dictionary mod).  I was mainly speaking about the raw ores... and how those looking the same doesn't really matter as much, at least not with my setup.  I'm sure somebody would complain though hahaha.

**Comment by MarikCZ** [comment]
I fully undestand you. :) Conversation with you is so funny. :D "hahaha"
